// IPC channel names shared by main (ipcMain.handle) and preload (ipcRenderer.invoke).
// One channel per QuantApi method — see src/shared/types.ts for signatures.

export const IPC = {
  watchlistGet: 'watchlist:get',
  watchlistAdd: 'watchlist:add',
  watchlistRemove: 'watchlist:remove',
  watchlistReorder: 'watchlist:reorder',
  symbolsSearch: 'symbols:search',
  quotesGet: 'quotes:get',
  holdingsGet: 'holdings:get',
  newsGet: 'news:get',
  earningsGet: 'earnings:get',
  chartGet: 'chart:get',
  chartGetV3: 'chart:get-v3',
  chartPrefetchV3: 'chart:prefetch-v3',
  marketCacheStats: 'market-cache:stats',
  marketCachePrune: 'market-cache:prune',
  pivotNewsGet: 'chart:pivot-news',
  macroOverlayGet: 'chart:macro-overlay',
  chartSnapshotCapture: 'chart:capture-snapshot',
  quantAnalyze: 'quant:analyze',
  quantInsightsGet: 'quant:insights-get',
  quantJournalGet: 'quant:journal-get',
  quantJournalSave: 'quant:journal-save',
  llmSettingsGet: 'llm-settings:get',
  llmSettingsSave: 'llm-settings:save',
  llmConnectionTest: 'llm-settings:test',
  valuationGet: 'valuation:get',
  signalsScan: 'signals:scan',
  signalDeskGet: 'signal-desk:get',
  chartEventsGet: 'chart:events-get',
  signalHistoryGet: 'signal-history:get',
  signalHistoryMigrate: 'signal-history:migrate',
  portfolioGet: 'portfolio:get',
  portfolioSnapshotGet: 'portfolio:snapshot-get',
  portfolioRiskGet: 'portfolio:risk-get',
  portfolioExposureGet: 'portfolio:exposure-get',
  portfolioSymbolContextGet: 'portfolio:symbol-context-get',
  portfolioAccountAdd: 'portfolio:account-add',
  portfolioLotAdd: 'portfolio:lot-add',
  portfolioLotUpdate: 'portfolio:lot-update',
  portfolioLotRemove: 'portfolio:lot-remove',
  portfolioCashSet: 'portfolio:cash-set',
  portfolioCsvPreview: 'portfolio:csv-preview',
  portfolioCsvImport: 'portfolio:csv-import',
  discoveryHydrationStatus: 'discovery:hydration-status',
  discoveryHydrationStart: 'discovery:hydration-start',
  discoveryHydrationStop: 'discovery:hydration-stop',
  discoveryRun: 'discovery:run',
  discoveryLatest: 'discovery:latest',
  forecastRun: 'forecast:run',
  forecastCancel: 'forecast:cancel',
  forecastGetJob: 'forecast:get-job',
  forecastListSaved: 'forecast:list-saved',
  forecastGetSaved: 'forecast:get-saved',
  forecastGetHistoricalComparison: 'forecast:get-historical-comparison',
  forecastSetOverlayEnabled: 'forecast:set-overlay-enabled',
  forecastGetOverlayEnabled: 'forecast:get-overlay-enabled',
  forecastProgress: 'forecast:progress',
  forecastCompleted: 'forecast:completed',
  forecastFailed: 'forecast:failed',
  openExternal: 'shell:open-external',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
